server:
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      suffix: .html
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        order_inserts: true
#        order_updates: true
#      generate-ddl: true
#      show-sql: true
#    database: ${database}
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#  datasource:
#    url: ${datasource}

google:
  key: ${GOOGLE_API_KEY}