sample:
  value: default

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      suffix: .html